name: spread
on:
  push:
    branchs:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get-diff
        run: echo "DIFF=${git diff ${{ github.event.before }} ${{ github.event.after }} --name-status}" >> $GITHUB_ENV
        run: echo ${{ env.DIFF }}
      # - name: start
      #   uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      #   with:
      #     host: ${{ secrets.HOST_SERVER }}
      #     user: ${{ secrets.USERNAME_SERVER }}
      #     pass: ${{ secrets.PASSWORD_SERVER }}
      #     connect_timeout: 10s
      #     scp: |
      #       './*/*.md' => /var/www/server/static/articles
      #       'tag.json' => /var/www/server/static/articles
      #     last_ssh: |
      #       source /var/www/server/deployed/uploadArticles.sh